#!/usr/bin/env bash
# assets/temas-de-apps/toolkits-gtk-qt/manifesto.sh — GTK3, GTK4 e Qt5/Qt6 (qt5ct/qt6ct).
#
# ESTE ARQUIVO É `source`: nada de `exit`, nada de `set -e`.
#
# ============================================================================
# A RESPOSTA CURTA: QUASE TUDO AQUI JÁ VEM DE GRAÇA. E ISSO FOI MEDIDO.
# ============================================================================
# O `cosmic-settings-daemon` é a ponte entre o tema do COSMIC e os toolkits que
# não são COSMIC. Com `CosmicTk/apply_theme_global = true` ele regenera, a cada
# mudança de tema, TODOS estes arquivos — medido em 2026-08-04 com mtimes
# idênticos ao milissegundo:
#
#     ~/.config/gtk-3.0/gtk.css                  (SYMLINK -> o css abaixo)
#     ~/.config/gtk-4.0/gtk.css                  (SYMLINK -> o css abaixo)
#     ~/.config/gtk-4.0/cosmic/{dark,light}.css  ("/* GENERATED BY COSMIC */")
#     ~/.config/qt5ct/colors/Cosmic{Dark,Light}.conf
#     ~/.config/qt6ct/colors/Cosmic{Dark,Light}.conf
#     ~/.config/qt5ct/qt5ct.conf   e   ~/.config/qt6ct/qt6ct.conf
#     ~/.config/kdeglobals
#     ~/.local/share/color-schemes/Cosmic{Dark,Light}.colors
#
# Quem escreve é o binário `/usr/bin/cosmic-settings-daemon`, e ele é o ÚNICO em
# /usr/bin que contém a string "GENERATED BY COSMIC" — conferido com
# `cd /usr/bin && grep -rl --binary-files=binary "GENERATED BY COSMIC" .`, que
# devolve exatamente uma linha. As outras strings do mesmo binário desenham o
# resto do mapa: `qt5ct`, `qt6ct`, `cosmic_qt_version`, `color_scheme_path`,
# `custom_palette`, `icon_theme`, `breeze`, `breeze-dark`, `CosmicDark.conf`,
# `kdeglobals`, `color-schemes` e até um
# `assertion failed: ct == "qt5ct" || ct == "qt6ct"`.
#
# Portanto: NÃO existe "aplicar Catppuccin no GTK" nem "aplicar Catppuccin no
# Qt" como tarefa separada. Quem pinta os dois é o tema do COSMIC. Trocar o
# tema do COSMIC para Catppuccin Mocha repinta GTK3, GTK4, Qt5, Qt6 e KDE de
# uma vez só. Este módulo, por isso, é 90% conferência e 10% conserto.
#
# ---------------------------------------------------------------------------
# POR QUE NÃO USAMOS O catppuccin/qt5ct (existe, foi conferido)
# ---------------------------------------------------------------------------
# https://github.com/catppuccin/qt5ct existe mesmo (conferido por WebFetch em
# 2026-08-04: "Soothing pastel theme for qt5ct & qt6ct", 6 commits no main) e
# entrega arquivos estáticos tipo `assets/temas/catppuccin-mocha-mauve.conf`.
# NÃO usamos, de propósito: apontar `color_scheme_path` para um arquivo estático
# é declarar guerra ao daemon, que reescreve essa mesma chave para o
# `colors/CosmicDark.conf` a cada regeneração. Perderíamos a briga a cada
# mudança de tema — e, pior, a paleta ficaria CONGELADA, deixando de seguir o
# accent dela. O caminho certo é deixar o COSMIC gerar a partir do tema.
#
# ---------------------------------------------------------------------------
# O ÚNICO BURACO REAL: O TEMA DE ÍCONES DO Qt
# ---------------------------------------------------------------------------
# O daemon preenche `[Appearance]/icon_theme` do qt5ct/qt6ct com `breeze-dark`
# (ou `breeze` no claro) — valores HARDCODED no binário, ao lado da própria
# chave `icon_theme`. Ele NÃO lê o `CosmicTk/icon_theme` da usuária. Resultado
# de fábrica: o COSMIC mostra MeowSystem-Icons e todo app Qt mostra breeze-dark.
#
# A semântica exata foi medida com dois experimentos (não por leitura de
# strings — a lição da Steam vale: string de binário não substitui teste):
#
#   EXPERIMENTO 1 (04/08/2026) — escrevi `icon_theme=MeowSystem-Icons`, esperei
#   3s, forcei uma regeneração. O daemon reescreveu os 4 arquivos (mtime
#   20:15:21, três segundos DEPOIS da minha escrita) e o valor SOBREVIVEU.
#   => o daemon faz MERGE do qt5ct.conf; ele não atropela a chave.
#
#   EXPERIMENTO 2 (04/08/2026) — apaguei a chave `icon_theme` e forcei outra
#   regeneração. Voltou `icon_theme=breeze-dark`.
#   => `breeze-dark` é DEFAULT-QUANDO-AUSENTE, não valor forçado.
#
# Como forçar uma regeneração sem mexer no tema dela: reescrever um arquivo de
# `com.system76.CosmicTheme.Dark/v1/` com os MESMOS bytes. O inotify dispara por
# escrita, não por mudança de conteúdo — logo o tema dela não muda em nada.
#
# ---------------------------------------------------------------------------
# A CONCLUSÃO DE 04/08 ESTAVA ERRADA PELA METADE — MEDIDO EM 09/09/2026
# ---------------------------------------------------------------------------
# O que estava escrito aqui, e que este parágrafo REVOGA:
#
#     "escrever essa chave é DURÁVEL (sobrevive a troca de tema e a reinício de
#      sessão) (…) o módulo é auto-curável sem ficar brigando com ninguém."
#
# A primeira metade continua verdadeira. A segunda — "e a reinício de sessão" —
# nunca foi, e o campo cobrou por 36 dias em silêncio: 29 reparos entre 04/08 e
# 06/09/2026, um por pasta datada em
#
#     ls -d ~/.local/state/meowsystem/backups/*/.config/qt5ct
#
# Ou seja: o módulo NÃO era auto-curável — ele era curado, todo dia, pelo doctor
# das 5h da manhã, e entre o login e essa hora todo aplicativo Qt dela ficava com
# o ícone errado. O `~~ qt5ct.conf: icon_theme=MeowSystem-Icons` seguido, na
# passagem seguinte, de `qt5ct.conf: icon_theme=breeze-dark` no `doctor.log` era
# esse laço aparecendo, e ninguém o tinha lido como laço.
#
#   EXPERIMENTO 3 (09/09/2026) — O EXPERIMENTO 1, REFEITO COM CANÁRIAS.
#   Semeei o `qt5ct.conf` com `icon_theme=MeowSystem-Icons` MAIS duas chaves que
#   o daemon não conhece — `meow_canario=1` dentro do `[Appearance]` e uma seção
#   `[Fonts]` inteira — e forcei a regeneração de dois jeitos: (a) reescrevendo
#   `CosmicTheme.Dark/v1/accent` com os mesmos bytes e (b) idem com
#   `CosmicTheme.Mode/v1/is_dark`. Nos dois casos o daemon regravou os `.conf`
#   em milissegundos, REORDENOU as chaves (ele serializa a partir de um mapa) e
#   devolveu TUDO de pé: as duas canárias e o `MeowSystem-Icons`.
#   => o EXPERIMENTO 1 continua válido, e agora com prova mais forte: o merge é
#      um round-trip de verdade, não uma coincidência de chaves conhecidas.
#
#   EXPERIMENTO 4 (09/09/2026) — ENTÃO QUEM REESCREVE? A PARTIDA DA SESSÃO.
#   Não é troca de tema: nada em `~/.config/cosmic` foi escrito na hora do
#   estrago (`find ~/.config/cosmic -newermt …` devolve vazio), e o tema dela
#   está parado desde 25/08. O carimbo do dia, com milissegundo:
#
#       09:13:39  boot
#       09:14:21  cosmic-settings-daemon nasce (PID 3631, `ps -o lstart`)
#       09:14:23.513  ele grava o PRÓPRIO estado (…/CosmicSettingsDaemon/v1/
#                     default_sink_name)
#       09:14:23.686 … .874  os TREZE arquivos gerados, numa rajada de 190 ms,
#                     terminando em qt5ct.conf (.866) e qt6ct.conf (.874), os
#                     dois com `icon_theme` de volta em `breeze-dark`
#
#   E a prova de que foi SÓ isso: os dois `.conf` tinham nascido às 05:07:21 de
#   06/09 (o reparo do doctor daquele dia) e ficaram com o mtime PARADO por três
#   dias — atravessaram os doctors de 07/09, 08/09 e 09/09 às 05:0x dizendo
#   "nada a consertar". A única escrita em 72 horas foi a das 09:14:23.
#   => `breeze-dark` não é só DEFAULT-QUANDO-AUSENTE. Na EXPORTAÇÃO DE PARTIDA
#      do daemon ele é valor IMPOSTO: o merge do regime permanente não vale ali.
#
#   O DETALHE QUE IMPEDE DE DIZER "TODO LOGIN": o boot de 08/09 21:38 NÃO
#   derrubou a chave (o mtime prova), e naquele boot o daemon também não gravou o
#   `default_sink_name` — a exportação de partida não chegou a rodar. Cruzando os
#   29 reparos com `last -x reboot`: dos 28 que têm reparo anterior para
#   comparar, 23 tiveram boot na janela; os 5 que não tiveram caem todos em dois
#   dias de oficina (04/08 e 25/08), quando o `aplicar` foi chamado à mão. Nenhum
#   reparo de dia normal aconteceu sem um boot antes dele. Então: QUASE todo
#   login, não todo login.
#
# O QUE MUDOU NO PROJETO POR CAUSA DISSO
#   Nasceram `systemd/meow-qt.path` e `systemd/meow-qt.service` (09/09/2026): um
#   vigia de inotify sobre `~/.config/qt5ct` e `~/.config/qt6ct` que chama este
#   mesmo módulo quando alguém mexe nos `.conf`. O conserto continua sendo o
#   `meow_app_aplicar` daqui — o vigia só arranjou o EVENTO, como o
#   `meow-fundo.path` fez pelo carrossel. A espera dela caiu de "até as 5h da
#   manhã" para dois segundos. O cabeçalho do `.path` traz a medição inteira,
#   inclusive por que congelar o arquivo (`chattr +i`) seria pior: mataria junto
#   a regeneração da PALETA, que é o que faz o Qt seguir o accent dela.
#
#   Não há laço com o daemon: ele NÃO vigia o `qt5ct.conf`, só o escreve —
#   medido em 09/09, as escritas nossas no arquivo não produziram nenhuma
#   resposta dele.
#
# ---------------------------------------------------------------------------
# UMA VARIÁVEL DE AMBIENTE COBRE Qt5 E Qt6 (era a minha suspeita errada)
# ---------------------------------------------------------------------------
# `QT_QPA_PLATFORMTHEME=qt5ct` vem de `/etc/X11/Xsession.d/99qt5ct` (existe,
# 213 bytes, de 2020). Eu suspeitei que apps Qt6 ficassem sem tema, porque não
# existe `libqt5ct.so` no diretório de plugins do Qt6. ESTAVA ERRADO, e o teste
# mostrou o porquê:
#
#     QT_QPA_PLATFORM=offscreen QT_DEBUG_PLUGINS=1 qt6ct
#     -> Got keys from plugin meta data QList("qt6ct", "qt5ct")
#
# O `libqt6ct.so` do Debian/Ubuntu declara os DOIS nomes, justamente para que a
# variável única funcione nos dois toolkits. O plugin carregou e leu
# `~/.config/qt6ct`. Ou seja: Qt5 e Qt6 estão ambos cobertos, e NÃO se deve
# mexer em `QT_QPA_PLATFORMTHEME` — trocar para `qt6ct` quebraria o Qt5, que não
# tem o alias recíproco.
#
# ---------------------------------------------------------------------------
# KVANTUM: NÃO INSTALAR (a ausência dele é uma feature)
# ---------------------------------------------------------------------------
# Kvantum não está instalado, e não deve ser. O estilo do Kvantum PINTA por
# conta própria e ignora a paleta do qt5ct — instalar o Kvantum desligaria
# exatamente a sincronia com o tema do COSMIC que faz tudo isto funcionar de
# graça. Se um dia ela quiser assumir o controle manual, o comando é
# `sudo apt install qt5-style-kvantum qt5-style-kvantum-themes`; o módulo avisa,
# mas não instala nem remove nada.
#
# ---------------------------------------------------------------------------
# O QUE NUNCA SE FAZ AQUI
# ---------------------------------------------------------------------------
# `~/.config/gtk-3.0/gtk.css` e `~/.config/gtk-4.0/gtk.css` são SYMLINKS para
# `~/.config/gtk-4.0/cosmic/dark.css`. Este módulo só faz `readlink` neles.
# Nunca escreve, nunca copia para backup com `cp` sem `-P`: um `cp` de volta os
# transformaria em arquivo comum, e aí a regeneração do COSMIC morre para
# sempre — o daemon passaria a sobrescrever um arquivo em vez de manter o link.
#
# ---------------------------------------------------------------------------
# TRÊS ARMADILHAS QUE APARECERAM MEDINDO, E ONDE ELAS MORAM NO CÓDIGO
# ---------------------------------------------------------------------------
# 1. `conferir` E `aplicar` TÊM DE ENXERGAR A MESMA COISA. A primeira versão
#    deste módulo marcava divergência para qualquer gtk.css que não fosse o
#    symlink esperado — inclusive um symlink apontando para um css DELA, que
#    `aplicar` (com toda a razão) se recusa a tocar. Reproduzido em sandbox:
#    `conferir` devolvia 1 para sempre e `aplicar` devolvia 0 "nada a fazer",
#    de hora em hora, sem nunca convergir. Agora quem classifica é
#    `_meow_tk_gtk_estado`, e SÓ o estado que `aplicar` sabe consertar conta
#    como divergência.
#
# 2. BACKUP POR `basename` PERDE ARQUIVO. `gtk-3.0/gtk.css` e `gtk-4.0/gtk.css`
#    têm o mesmo basename: no cenário em que os dois viram arquivo comum, o
#    segundo backup apagava o primeiro EM SILÊNCIO (reproduzido — sobrava um
#    único `gtk.css` na pasta, e sem o caminho original ninguém saberia de qual
#    toolkit ele era). O backup agora espelha o caminho relativo ao HOME e
#    escreve `origens.txt`, que é o formato que os módulos vizinhos (vscode,
#    btop-bat) já usam na MESMA pasta compartilhada.
#
# 3. NÃO SE INVENTA `qt5ct.conf`. Se o arquivo não existe, quem o cria é o
#    daemon. Escrever um `[Appearance]/icon_theme` sozinho produzia um .conf
#    sem `custom_palette` nem `color_scheme_path` — e o próprio `conferir`
#    passava a reclamar de "fora da sincronia do COSMIC" a cada passagem, sobre
#    um arquivo que este módulo tinha acabado de criar (e que, por não existir
#    antes, não tinha backup nenhum para desfazer). Agora ele pula e diz por
#    quê: na primeira troca de tema o daemon cria, e aí o ícone entra.

# --- constantes -------------------------------------------------------------
MEOW_TK_GTK3_CSS="$HOME/.config/gtk-3.0/gtk.css"
MEOW_TK_GTK4_CSS="$HOME/.config/gtk-4.0/gtk.css"
MEOW_TK_COSMIC_CSS_DIR="$HOME/.config/gtk-4.0/cosmic"
MEOW_TK_TK_DIR="$HOME/.config/cosmic/com.system76.CosmicTk/v1"
MEOW_TK_QT5_CONF="$HOME/.config/qt5ct/qt5ct.conf"
MEOW_TK_QT6_CONF="$HOME/.config/qt6ct/qt6ct.conf"

# Diretório de backup desta execução, resolvido na primeira vez que precisa.
MEOW_TK_BACKUP_DIR=""

# --- utilidades -------------------------------------------------------------

# Lê um valor do CosmicTk (formato RON) e devolve sem as aspas.
_meow_tk_ler_tk() {
  local chave="${1:-}" bruto=""
  [ -r "$MEOW_TK_TK_DIR/$chave" ] || return 1
  bruto="$(cat "$MEOW_TK_TK_DIR/$chave" 2>/dev/null)" || return 1
  bruto="${bruto%\"}"; bruto="${bruto#\"}"
  printf '%s' "$bruto"
}

# Lê `chave=valor` da seção [Appearance] de um .conf estilo QSettings.
#
# A chave viaja pelo AMBIENTE, não por `awk -v`: o `-v` processa sequências de
# escape (uma barra invertida no valor vira outra coisa), e `ENVIRON` entrega o
# texto cru. Aqui a chave é literal, mas o mesmo helper serve para valores
# vindos da config dela — o hábito é o que evita a surpresa.
_meow_tk_ini_ler() {
  local arquivo="${1:-}" chave="${2:-}"
  [ -r "$arquivo" ] || return 1
  MEOW_INI_CHAVE="$chave" awk '
    BEGIN { chave = ENVIRON["MEOW_INI_CHAVE"]; achou = 0 }
    /^\[/ { na = ($0 == "[Appearance]"); next }
    na && index($0, chave "=") == 1 { print substr($0, length(chave) + 2); achou = 1; exit }
    END { if (!achou) exit 1 }
  ' "$arquivo"
}

# Devolve no stdout o conteúdo do arquivo com `chave=valor` na seção
# [Appearance]. MERGE de verdade, linha a linha: toda outra chave (dela ou do
# daemon — color_scheme_path, custom_palette, cosmic_qt_version,
# standard_dialogs) sai intacta e na mesma ordem.
#
# As linhas em branco ficam num buffer para que a chave nova entre ANTES delas,
# e não depois: sem isso a chave caía entre a linha vazia e o `[Fonts]`
# seguinte. É válido para o QSettings, mas rende um diff torto na config dela
# — e config torta é o tipo de coisa que ninguém confere de novo.
_meow_tk_ini_definir() {
  local arquivo="${1:-}" chave="${2:-}" valor="${3:-}"
  if [ ! -r "$arquivo" ]; then
    printf '[Appearance]\n%s=%s\n' "$chave" "$valor"
    return 0
  fi
  MEOW_INI_CHAVE="$chave" MEOW_INI_VALOR="$valor" awk '
    BEGIN { chave = ENVIRON["MEOW_INI_CHAVE"]; valor = ENVIRON["MEOW_INI_VALOR"]
            posto = 0; na = 0; viu = 0; nbuf = 0 }
    function despejar(   i) { for (i = 1; i <= nbuf; i++) print buf[i]; nbuf = 0 }
    function por() { if (!posto) { print chave "=" valor; posto = 1 } }
    /^\[/ {
      if (na) por()
      despejar()
      na = ($0 == "[Appearance]"); if (na) viu = 1
      print; next
    }
    /^[ \t]*$/ { buf[++nbuf] = $0; next }
    {
      despejar()
      # troca no lugar, preservando a posição original da chave
      if (na && index($0, chave "=") == 1) { por(); next }
      print
    }
    END {
      if (na) por()
      vazias = nbuf
      despejar()
      if (!viu) {
        if (!vazias && NR > 0) print ""
        printf "[Appearance]\n%s=%s\n", chave, valor
      }
    }
  ' "$arquivo"
}

# --- backup (regra 4: antes de sobrescrever, SEMPRE) ------------------------
# O caminho dentro do backup é RELATIVO AO HOME, e isso não é enfeite: é a
# armadilha 2 do cabeçalho (dois `gtk.css` disputando o mesmo nome). O
# `origens.txt` existe porque sem o caminho absoluto original um "desfazer" não
# saberia para onde devolver o arquivo.
#
# `cp -P` é OBRIGATÓRIO: sem ele um symlink viraria cópia do alvo, e restaurar
# esse backup mataria a regeneração do COSMIC — que é exatamente o defeito que
# este módulo existe para consertar.
#
# O carimbo usa hífen (`%Y-%m-%dT%H-%M-%S`) e não `date -Iseconds` porque a
# pasta `backups/` é COMPARTILHADA por todos os módulos: em ASCII o `-` (0x2D)
# vem antes do `:` (0x3A), então misturar os dois formatos faria toda pasta com
# hífen parecer mais antiga que qualquer uma com dois pontos. `MEOW_CARIMBO` é
# a variável que os módulos vizinhos usam para caírem todos na mesma pasta.
_meow_tk_backup() {
  local origem="${1:-}" rel="" destino=""
  # `-L` junto com `-e` para que um symlink QUEBRADO também seja preservado.
  [ -e "$origem" ] || [ -L "$origem" ] || return 0
  meow_seco && return 0
  if [ -z "$MEOW_TK_BACKUP_DIR" ]; then
    MEOW_TK_BACKUP_DIR="${MEOW_ESTADO:-$HOME/.local/state/meowsystem}/backups/${MEOW_CARIMBO:-$(date +%Y-%m-%dT%H-%M-%S)}"
  fi
  case "$origem" in
    "$HOME"/*) rel="${origem#"$HOME"/}" ;;
    *)         rel="fora-da-home/${origem#/}" ;;
  esac
  destino="$MEOW_TK_BACKUP_DIR/$rel"
  mkdir -p "$(dirname "$destino")" || return 1
  cp -P --preserve=all -- "$origem" "$destino" || return 1
  printf '%s\n' "$origem" >> "$MEOW_TK_BACKUP_DIR/origens.txt" || return 1
  # Soma só de arquivo comum: `sha256sum` num symlink seguiria o alvo (e num
  # link quebrado falharia), transformando um backup fiel em erro de execução.
  if [ ! -L "$origem" ] && [ -f "$origem" ]; then
    ( cd "$MEOW_TK_BACKUP_DIR" && sha256sum -- "$rel" >> manifesto.sha256 ) || return 1
  fi
  meow_info "backup: $destino"
  return 0
}

# Qual css o COSMIC gerou (o alvo legítimo dos symlinks). Escuro primeiro.
_meow_tk_css_gerado() {
  local c
  for c in "$MEOW_TK_COSMIC_CSS_DIR/dark.css" "$MEOW_TK_COSMIC_CSS_DIR/light.css"; do
    if [ -r "$c" ]; then printf '%s' "$c"; return 0; fi
  done
  return 1
}

# Classifica o gtk.css em UMA palavra. É esta função que mantém `conferir` e
# `aplicar` enxergando a mesma realidade (armadilha 1 do cabeçalho):
#
#   ok                 symlink para o css que o COSMIC gera — nada a fazer
#   link-quebrado      symlink certo, alvo ainda não gerado — é com o COSMIC
#   link-alheio        symlink para outro lugar — escolha dela, não se toca
#   arquivo-igual      arquivo comum, byte a byte igual ao css gerado (típico
#                      de backup restaurado por cima) — ISTO nós religamos
#   arquivo-proprio    arquivo comum com conteúdo diferente — pode ser css dela
#   arquivo-sem-fonte  arquivo comum e não há css gerado para comparar
#   ausente            não existe — quem cria é o COSMIC
_meow_tk_gtk_estado() {
  local css="${1:-}" alvo="" gerado=""
  if [ -L "$css" ]; then
    alvo="$(readlink -m -- "$css")"
    case "$alvo" in
      "$MEOW_TK_COSMIC_CSS_DIR"/*.css)
        if [ -e "$css" ]; then printf 'ok'; else printf 'link-quebrado'; fi ;;
      *) printf 'link-alheio' ;;
    esac
    return 0
  fi
  if [ ! -e "$css" ]; then printf 'ausente'; return 0; fi
  if ! gerado="$(_meow_tk_css_gerado)"; then printf 'arquivo-sem-fonte'; return 0; fi
  if cmp -s "$css" "$gerado"; then printf 'arquivo-igual'; else printf 'arquivo-proprio'; fi
  return 0
}

# `gtk-3.0/gtk.css` em vez do caminho absoluto: as mensagens ficam legíveis e
# ainda dá para distinguir os dois de relance.
_meow_tk_curto() { printf '%s/%s' "$(basename "$(dirname "${1:-}")")" "$(basename "${1:-}")"; }

_meow_tk_qt_presente() { meow_tem qt5ct || meow_tem qt6ct; }

# A ferramenta correspondente a este .conf está instalada?
_meow_tk_conf_vale() {
  case "${1:-}" in
    *qt5ct*) meow_tem qt5ct ;;
    *qt6ct*) meow_tem qt6ct ;;
    *) return 1 ;;
  esac
}

# ============================================================================
# 1. DETECTAR
# ============================================================================
# O "app" deste módulo é a ponte COSMIC -> toolkits. Sem o daemon que a
# constrói não há o que conferir nem o que consertar: devolve 3, nunca erro.
meow_app_detectar() {
  if ! meow_tem cosmic-settings-daemon && [ ! -d "$MEOW_TK_TK_DIR" ]; then
    return "$MEOW_SEM_DEPENDENCIA"
  fi
  return "$MEOW_OK"
}

# ============================================================================
# 2. CONFERIR (somente leitura)
# ============================================================================
# REGRA DESTE MÓDULO: só marca `divergente` aquilo que `aplicar` sabe
# consertar. Todo o resto é aviso — informação para ela, não tarefa pendente
# para o robô repetir de hora em hora sem nunca fechar.
meow_app_conferir() {
  meow_app_detectar || return "$MEOW_SEM_DEPENDENCIA"

  local divergente=0 global="" icone_cosmic="" atual="" curto=""

  # --- a chave-mestra -------------------------------------------------------
  # Sem `apply_theme_global=true` NADA deste módulo acontece: o daemon para de
  # gerar css do GTK e paleta do Qt, e os dois toolkits caem no visual de
  # fábrica. É a única chave que vale a pena vigiar do lado do COSMIC.
  global="$(_meow_tk_ler_tk apply_theme_global || printf 'ausente')"
  if [ "$global" = "true" ]; then
    meow_ok "CosmicTk apply_theme_global=true — o COSMIC pinta GTK e Qt sozinho"
  else
    meow_aviso "apply_theme_global=$global — GTK e Qt NÃO estão seguindo o tema"
    divergente=1
  fi

  # --- GTK3 / GTK4: só conferência, nunca escrita ---------------------------
  local css
  for css in "$MEOW_TK_GTK3_CSS" "$MEOW_TK_GTK4_CSS"; do
    curto="$(_meow_tk_curto "$css")"
    case "$(_meow_tk_gtk_estado "$css")" in
      ok)
        meow_ok "$curto -> $(readlink -- "$css")" ;;
      arquivo-igual)
        meow_muda "$curto é arquivo comum, cópia exata do css gerado — dá para religar o symlink"
        divergente=1 ;;
      arquivo-proprio)
        meow_aviso "$curto é arquivo comum com conteúdo PRÓPRIO — não mexo; apague-o se quiser o COSMIC de volta" ;;
      arquivo-sem-fonte)
        meow_aviso "$curto é arquivo comum e não há css do COSMIC para comparar" ;;
      link-alheio)
        meow_aviso "$curto aponta para $(readlink -- "$css") — fora do COSMIC; é escolha sua, não mexo" ;;
      link-quebrado)
        meow_aviso "$curto aponta para um css que ainda não existe — o COSMIC gera na próxima troca de tema" ;;
      ausente)
        meow_info "$curto ainda não existe — quem gera é o COSMIC, não este módulo" ;;
    esac
  done

  # --- Qt: paleta é do COSMIC; ícone é nosso --------------------------------
  if ! _meow_tk_qt_presente; then
    meow_pula "qt5ct/qt6ct ausentes — nenhum app Qt para tematizar"
    meow_info "se quiser: sudo apt install qt5ct qt6ct"
    [ "$divergente" = "1" ] && return "$MEOW_DIVERGENTE"
    return "$MEOW_OK"
  fi

  if meow_tem kvantummanager || [ -d "$HOME/.config/Kvantum" ]; then
    # Não é divergência: é escolha dela. Mas ela precisa saber do efeito.
    meow_aviso "Kvantum instalado — o estilo dele IGNORA a paleta do qt5ct e desliga a sincronia com o COSMIC"
  fi

  icone_cosmic="$(_meow_tk_ler_tk icon_theme || printf '')"
  if [ -z "$icone_cosmic" ]; then
    meow_pula "CosmicTk sem icon_theme — deixo o breeze-dark do COSMIC em paz"
    [ "$divergente" = "1" ] && return "$MEOW_DIVERGENTE"
    return "$MEOW_OK"
  fi

  local conf
  for conf in "$MEOW_TK_QT5_CONF" "$MEOW_TK_QT6_CONF"; do
    # Só cobra o .conf cuja ferramenta existe de fato.
    _meow_tk_conf_vale "$conf" || continue
    if [ ! -e "$conf" ]; then
      # Não é divergência: `aplicar` também não vai criar (armadilha 3).
      meow_pula "$(basename "$conf") ainda não existe — quem cria é o cosmic-settings-daemon"
      continue
    fi
    atual="$(_meow_tk_ini_ler "$conf" icon_theme || printf 'ausente')"
    if [ "$atual" = "$icone_cosmic" ]; then
      meow_ok "$(basename "$conf"): icon_theme=$atual"
    else
      meow_muda "$(basename "$conf"): icon_theme=$atual (o COSMIC usa '$icone_cosmic')"
      divergente=1
    fi

    # A paleta em si é do daemon. Só reporto, não conserto: consertar aqui
    # seria mexer numa chave que o COSMIC reescreve na próxima regeneração.
    local paleta
    paleta="$(_meow_tk_ini_ler "$conf" color_scheme_path || printf 'ausente')"
    case "$paleta" in
      */colors/Cosmic*.conf) meow_ok "$(basename "$conf"): paleta gerada pelo COSMIC" ;;
      *) meow_aviso "$(basename "$conf"): color_scheme_path=$paleta — fora da sincronia do COSMIC" ;;
    esac
  done

  [ "$divergente" = "1" ] && return "$MEOW_DIVERGENTE"
  return "$MEOW_OK"
}

# ============================================================================
# 3. APLICAR
# ============================================================================
meow_app_aplicar() {
  meow_app_detectar || return "$MEOW_SEM_DEPENDENCIA"

  local mudou=0 erro=0 global="" icone_cosmic="" conteudo="" atual="" curto=""

  # --- 1. a chave-mestra ----------------------------------------------------
  global="$(_meow_tk_ler_tk apply_theme_global || printf 'ausente')"
  if [ "$global" != "true" ]; then
    if _meow_tk_backup "$MEOW_TK_TK_DIR/apply_theme_global"; then
      # `meow_escrever` grava com `printf '%s'`, SEM quebra de linha final — e
      # é assim que o cosmic-config guarda: o arquivo real tem 4 bytes, `true`.
      meow_escrever "$MEOW_TK_TK_DIR/apply_theme_global" "true" 644
      case $? in
        1) mudou=1; meow_muda "apply_theme_global=true (GTK e Qt voltam a seguir o tema)" ;;
        2) erro=1; meow_erro "não consegui ligar o apply_theme_global" ;;
      esac
    else
      erro=1; meow_erro "backup do apply_theme_global falhou — não escrevi"
    fi
  fi

  # --- 2. GTK: só o caso `arquivo-igual` ------------------------------------
  # Ou seja: alguém restaurou um backup por cima do symlink. Qualquer outro
  # estado é escolha dela ou tarefa do COSMIC — ver `_meow_tk_gtk_estado`.
  local css gerado
  for css in "$MEOW_TK_GTK3_CSS" "$MEOW_TK_GTK4_CSS"; do
    [ "$(_meow_tk_gtk_estado "$css")" = "arquivo-igual" ] || continue
    gerado="$(_meow_tk_css_gerado)" || continue
    curto="$(_meow_tk_curto "$css")"
    if meow_seco; then
      meow_muda "religaria o symlink $curto -> $gerado"
      mudou=1
      continue
    fi
    if ! _meow_tk_backup "$css"; then
      meow_erro "backup de $curto falhou — abortei o religamento"; erro=1; continue
    fi
    if ln -sfn "$gerado" "$css"; then
      mudou=1; meow_muda "symlink religado: $curto -> $gerado"
    else
      erro=1; meow_erro "falhei ao religar $curto"
    fi
  done

  # --- 3. Qt: o tema de ícones, a única escrita nossa deste lado -------------
  if ! _meow_tk_qt_presente; then
    meow_pula "qt5ct/qt6ct ausentes — nada a aplicar no Qt (sudo apt install qt5ct qt6ct)"
  else
    icone_cosmic="$(_meow_tk_ler_tk icon_theme || printf '')"
    if [ -z "$icone_cosmic" ]; then
      meow_pula "CosmicTk sem icon_theme — não invento tema de ícone para o Qt"
    else
      local conf
      for conf in "$MEOW_TK_QT5_CONF" "$MEOW_TK_QT6_CONF"; do
        _meow_tk_conf_vale "$conf" || continue
        if [ ! -e "$conf" ]; then
          # Armadilha 3: criar o .conf do zero produziria um arquivo sem
          # `custom_palette` nem `color_scheme_path`, e sem backup possível
          # (não havia arquivo antes). Quem cria é o daemon; eu completo depois.
          meow_pula "$(basename "$conf") não existe — o daemon cria na próxima troca de tema, e aí eu ponho o ícone"
          continue
        fi
        atual="$(_meow_tk_ini_ler "$conf" icon_theme || printf '')"
        [ "$atual" = "$icone_cosmic" ] && continue

        conteudo="$(_meow_tk_ini_definir "$conf" icon_theme "$icone_cosmic")"
        if [ -z "$conteudo" ]; then
          meow_erro "não consegui montar o conteúdo de $conf"; erro=1; continue
        fi
        # Backup antes de sobrescrever (regra 4). O `meow_escrever` cria o
        # temporário DENTRO de ~/.config/qtNct, então o mv é atômico mesmo com
        # o repo em /mnt/Apate.
        #
        # NÃO acrescente `\n` ao fim de `$conteudo`: o `meow_escrever` compara
        # com `"$(cat destino)"`, e o `$( )` come as quebras finais — conteúdo
        # com `\n` NUNCA seria igual ao lido de volta, e o arquivo seria
        # reescrito a cada passagem, matando a idempotência. O QSettings lê a
        # última linha sem newline sem reclamar, e o daemon repõe a quebra na
        # regeneração seguinte.
        if ! _meow_tk_backup "$conf"; then
          meow_erro "backup de $(basename "$conf") falhou — não escrevi"; erro=1; continue
        fi
        meow_escrever "$conf" "$conteudo" 644
        case $? in
          1) mudou=1; meow_muda "$(basename "$conf"): icon_theme=$icone_cosmic" ;;
          2) erro=1; meow_erro "falhei ao escrever $conf" ;;
        esac
      done
    fi
  fi

  # --- 4. veredito ----------------------------------------------------------
  [ "$erro" = "1" ] && return "$MEOW_ERRO"
  if [ "$mudou" = "0" ]; then
    meow_ok "GTK3, GTK4, Qt5 e Qt6 já seguem o tema do COSMIC — nada a fazer"
    return "$MEOW_OK"
  fi
  if meow_seco; then
    return "$MEOW_DIVERGENTE"
  fi
  # Apps Qt leem o qtNct.conf na largada; os já abertos só pegam o ícone novo
  # ao reabrir. Não reinicio nada: derrubar app dela para trocar ícone é pior
  # que esperar o próximo start.
  meow_registrar "toolkits-gtk-qt: aplicado (icon_theme=${icone_cosmic:-n/a})"
  return "$MEOW_DIVERGENTE"
}

# --- DESFAZER (11/08/2026) --------------------------------------------------
# Chegam aqui `meow apps reverter qt5ct|gtk|qt` e o passo 2/6 do `--uninstall`.
#
# ESTE É O MÓDULO CUJA REVERSÃO MAIS PODE DOER, E POR ISSO ELE É O MAIS ESTREITO
#   O que ele aplicou não é arte nossa: é a SINCRONIA entre o tema do COSMIC e os
#   dois toolkits. Desfazer não é apagar um tema, é cortar essa ligação — e um
#   corte mal feito deixa app GTK sem CSS nenhum ou app Qt apontando para um tema
#   de ícones que o desinstalador acabou de remover.
#
#   Então os três passos aqui devolvem VALORES DE FÁBRICA verificáveis, nunca
#   "o que ela tinha" (ninguém guardou isso), e cada um só age quando o estado
#   atual ainda é o nosso:
#
#     apply_theme_global  -> `false`, que é o padrão do COSMIC. Apagar o arquivo
#                            seria mais limpo no papel, mas o CosmicTk trata
#                            ausência e `false` de formas diferentes conforme a
#                            versão, e `false` é o que a interface dela mostra
#                            desmarcado.
#     symlink do gtk.css  -> vira ARQUIVO REAL com o mesmo conteúdo. É o estado
#                            em que o COSMIC deixa a máquina sozinho, e é o que
#                            havia antes de religarmos (ver `arquivo-igual` em
#                            `_meow_tk_gtk_estado`). Apagar o CSS deixaria os
#                            apps GTK sem a paleta que eles já usam hoje.
#     icon_theme do qtNct -> `$ICONES_BASE` (Papirus-Dark por padrão), um tema que
#                            EXISTE na máquina. Deixar `MeowSystem-Icons` seria
#                            apontar para a árvore que o passo 5/6 do
#                            desinstalador remove — apps Qt sem ícone nenhum.
_MEOW_TK_ICONES_FABRICA="${ICONES_BASE:-Papirus-Dark}"

meow_app_reverter() {
  meow_app_detectar || {
    meow_pula "sem COSMIC aqui — nada a desfazer nos toolkits"
    return "$MEOW_SEM_DEPENDENCIA"
  }

  local mudou=0 erro=0 css curto estado global conf atual conteudo tmp

  # --- 1. a chave global do CosmicTk ---------------------------------------
  global="$(_meow_tk_ler_tk apply_theme_global || printf 'ausente')"
  if [ "$global" = "true" ]; then
    if meow_seco; then
      meow_muda "apply_theme_global voltaria para false"; mudou=1
    elif _meow_tk_backup "$MEOW_TK_TK_DIR/apply_theme_global" \
         && printf '%s' "false" > "$MEOW_TK_TK_DIR/apply_theme_global" 2>/dev/null; then
      mudou=1; meow_muda "apply_theme_global=false (GTK e Qt deixam de seguir o COSMIC)"
    else
      erro=1; meow_erro "não consegui desligar o apply_theme_global"
    fi
  fi

  # --- 2. os symlinks do GTK ------------------------------------------------
  # Só desfazemos o link que aponta para DENTRO do diretório gerado pelo COSMIC
  # (`ok`). `link-alheio` é dela e não se toca — a mesma regra do aplicar.
  for css in "$MEOW_TK_GTK3_CSS" "$MEOW_TK_GTK4_CSS"; do
    estado="$(_meow_tk_gtk_estado "$css")"
    [ "$estado" = "ok" ] || continue
    curto="$(_meow_tk_curto "$css")"
    if meow_seco; then
      meow_muda "$curto voltaria a ser arquivo comum (hoje é symlink)"; mudou=1; continue
    fi
    if ! _meow_tk_backup "$css"; then
      erro=1; meow_erro "backup de $curto falhou — não desfiz o link"; continue
    fi
    # cp para um temporário ao lado e rename: sem isto, um corte entre o `rm` do
    # link e a cópia deixaria a máquina sem gtk.css nenhum.
    tmp="$(mktemp -p "$(dirname "$css")" ".meow.XXXXXX")" || { erro=1; continue; }
    if cp -L -- "$css" "$tmp" 2>/dev/null && chmod 644 "$tmp" && mv -f -- "$tmp" "$css"; then
      mudou=1; meow_muda "$curto: symlink desfeito, virou arquivo comum"
    else
      rm -f "$tmp"; erro=1; meow_erro "não consegui desfazer o link de $curto"
    fi
  done

  # --- 3. o icon_theme do qt5ct/qt6ct --------------------------------------
  if _meow_tk_qt_presente; then
    for conf in "$MEOW_TK_QT5_CONF" "$MEOW_TK_QT6_CONF"; do
      _meow_tk_conf_vale "$conf" || continue
      [ -f "$conf" ] || continue
      atual="$(_meow_tk_ini_ler "$conf" icon_theme || printf '')"
      # Só mexe se o valor de lá ainda for o tema que NÓS pusemos.
      [ "$atual" = "${NOME_TEMA_ICONES:-MeowSystem-Icons}" ] || continue
      if meow_seco; then
        meow_muda "$(basename "$conf"): icon_theme voltaria para $_MEOW_TK_ICONES_FABRICA"; mudou=1; continue
      fi
      if ! conteudo="$(_meow_tk_ini_definir "$conf" icon_theme "$_MEOW_TK_ICONES_FABRICA")"; then
        erro=1; meow_erro "não consegui montar o conteúdo de $conf"; continue
      fi
      if _meow_tk_backup "$conf" && printf '%s' "$conteudo" > "$conf" 2>/dev/null; then
        mudou=1; meow_muda "$(basename "$conf"): icon_theme=$_MEOW_TK_ICONES_FABRICA"
      else
        erro=1; meow_erro "não consegui escrever $conf"
      fi
    done
  fi

  [ "$erro" = "1" ] && return "$MEOW_ERRO"
  [ "$mudou" = "0" ] && { meow_ok "toolkits: já estavam sem a sincronia do MeowSystem"; return "$MEOW_OK"; }
  meow_seco || meow_ok "toolkits: GTK e Qt desligados do tema do COSMIC (vale ao reabrir os apps)"
  meow_seco || meow_info "tire 'qt5ct' de APPS_ATIVOS no meow.conf, ou o doctor das 05:00 reaplica"
  return "$MEOW_DIVERGENTE"
}
